import { z } from "zod";

import { INQUIRY_TYPES } from "../lib/constants/inquiry-types";


export const contactSubmissionSchema = z.strictObject({
  firstName: z.string({ error: "Enter your first name." })
    .trim()
    .min(1, "Enter your first name.")
    .max(100, "First name must be 100 characters or fewer."),

  lastName: z.string({ error: "Enter your last name." })
    .trim()
    .min(1, "Enter your last name.")
    .max(100, "Last name must be 100 characters or fewer."),

  email: z.string({ error: "Enter a valid email address." })
    .trim()
    .toLowerCase()
    .min(1, "Enter your email address.")
    .max(254, "Email must be 254 characters or fewer.")
    .pipe(z.email({ error: "Enter a valid email address." })),

  organizationName: z.string({ error: "Enter your organization name." })
    .trim()
    .min(1, "Enter your organization name.")
    .max(200, "Organization name must be 200 characters or fewer."),

  inquiryType: z.enum(INQUIRY_TYPES, {
    error: "Select a supported inquiry type.",
  }),

  message: z.string({ error: "Enter a message." })
    .trim()
    .min(1, "Enter a message.")
    .max(5_000, "Message must be 5,000 characters or fewer."),

  // --- Generated by the form; the same key must be reused on submission retries. ---
  submissionKey: z.uuid({ error: "Provide a valid submission UUID." }),
});

export type ContactSubmissionInput = z.input<typeof contactSubmissionSchema>;
export type ContactSubmissionDto = z.output<typeof contactSubmissionSchema>;
